name: moyasar_payment
description: Flutter library for Moyasar. Supports Apple Pay, STC Pay and Credit Card.
version: 0.1.5
homepage: https://mohammed-dev.com/
repository: https://github.com/mohammeddawida/moyasar_payment
issue_tracker: https://github.com/mohammeddawida/moyasar_payment/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: MoyasarPaymentPlugin
      android:
        package: com.example.moyasar_payment
        pluginClass: MoyasarPaymentPlugin
  
